[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
# Deploy script'inin deployments.json yazabilmesi için.
fs_permissions = [{ access = "read-write", path = "./deployments.json" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 10143, url = "https://testnet-rpc.monad.xyz" }
